[pytest]
# -n 2 అంటే రెండు బ్రౌజర్లు ఒకేసారి ఓపెన్ అవుతాయి (Parallel)
# --html అంటే రిపోర్ట్ జనరేట్ అవుతుంది
addopts = -n 2 --html=test_reports/report.html --self-contained-html

# టెస్ట్ ఫైల్స్ ఎక్కడున్నాయో ఇది చెబుతుంది
testpaths = test_scripts